# https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html#collections-galaxy-meta
namespace: puccini
name: tosca
version: 1.0.0
readme: README.md
authors:
- Puccini

license: Apache-2.0
homepage: https://puccini.cloud
repository: https://github.com/tliron/puccini
issues: https://github.com/tliron/puccini/issues
